# Generated by Django 5.2.13 on 2026-04-21 23:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('device_id', models.CharField(max_length=255)),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('operations_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lot de synchronisation',
                'verbose_name_plural': 'Lots de synchronisation',
                'db_table': 'sync_batches',
            },
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('local_id', models.CharField(max_length=100)),
                ('server_id', models.UUIDField(blank=True, null=True)),
                ('entity_type', models.CharField(max_length=50)),
                ('operation_type', models.CharField(choices=[('create', 'Création'), ('update', 'Mise à jour'), ('delete', 'Suppression')], max_length=10)),
                ('data', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='sync.syncbatch')),
            ],
            options={
                'verbose_name': 'Opération de synchronisation',
                'verbose_name_plural': 'Opérations de synchronisation',
                'db_table': 'sync_operations',
            },
        ),
    ]
