# Generated by Django 5.2.13 on 2026-04-21 23:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikelembaGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('contribution_amount', models.DecimalField(decimal_places=2, help_text='Montant de la cotisation journalière par membre (S)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('500'))])),
                ('security_levy', models.DecimalField(decimal_places=2, help_text='Prélèvement de sécurité par cotisation (a)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('penalty_rate_initial', models.FloatField(default=0.15, help_text='Taux de pénalité initial (alpha_0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('cycle_duration_days', models.PositiveIntegerField(help_text="Durée totale d'un cycle en jours (T)")),
                ('distribution_interval_days', models.PositiveIntegerField(default=3, help_text='Intervalle entre les distributions de cagnotte (k)')),
                ('reserve_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant actuel du fonds de réserve', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Groupe Likelemba',
                'verbose_name_plural': 'Groupes Likelemba',
                'db_table': 'likelemba_groups',
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('sequence_number', models.PositiveIntegerField(help_text="Numéro d'ordre du cycle")),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('total_contributions_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_refunds_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='tontines.likelembagroup')),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
                'db_table': 'cycles',
                'ordering': ['-sequence_number'],
                'unique_together': {('group', 'sequence_number')},
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('role', models.CharField(choices=[('member', 'Membre'), ('admin', 'Administrateur')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('queue_position', models.PositiveIntegerField(blank=True, null=True)),
                ('total_contributed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debt_count', models.PositiveIntegerField(default=0, help_text='Nombre de cotisations manquées')),
                ('has_received_payout', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tontines.likelembagroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adhésion',
                'verbose_name_plural': 'Adhésions',
                'db_table': 'memberships',
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='QueuePosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('position', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='tontines.cycle')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='tontines.membership')),
            ],
            options={
                'verbose_name': 'Position dans la file',
                'verbose_name_plural': 'Positions dans la file',
                'db_table': 'queue_positions',
                'ordering': ['position'],
                'unique_together': {('cycle', 'membership')},
            },
        ),
    ]
