# Generated by Django 5.2.13 on 2026-04-23 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='likelembagroup',
            name='invite_code',
            field=models.CharField(blank=True, help_text='Code unique pour les invitations', max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('message', models.TextField(blank=True, help_text='Message optionnel du demandeur')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True, help_text="Message de réponse de l'administrateur")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='tontines.likelembagroup')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_join_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'adhésion",
                'verbose_name_plural': "Demandes d'adhésion",
                'db_table': 'join_requests',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'group')},
            },
        ),
    ]
