# Generated by Django 5.2.13 on 2026-04-24 18:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0002_likelembagroup_invite_code_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='likelembagroup',
            name='current_beneficiary_index',
            field=models.PositiveIntegerField(default=0, help_text="Index du bénéficiaire actuel dans la file d'attente"),
        ),
        migrations.AddField(
            model_name='likelembagroup',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Verrouillage des paramètres après démarrage'),
        ),
        migrations.AddField(
            model_name='likelembagroup',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='likelembagroup',
            name='regeneration_target_days',
            field=models.PositiveIntegerField(default=3, help_text='Délai cible de régénération du fonds (ΔTmax)'),
        ),
        migrations.AlterField(
            model_name='likelembagroup',
            name='reserve_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant actuel du fonds de réserve – F(t)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='likelembagroup',
            name='security_levy',
            field=models.DecimalField(decimal_places=2, help_text='Prélèvement de sécurité par cotisation (a), en valeur absolue', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='likelembagroup',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Date de début du cycle (cycleStartDate)', null=True),
        ),
    ]
