# Generated by Django 5.2.13 on 2026-04-21 23:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tontines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transaction_type', models.CharField(choices=[('contribution', 'Cotisation'), ('refund', 'Remboursement'), ('payout', 'Cagnotte')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='proofs/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('is_synced', models.BooleanField(default=True)),
                ('local_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tontines.cycle')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tontines.membership')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'db_table': 'contributions',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transaction_type', models.CharField(choices=[('contribution', 'Cotisation'), ('refund', 'Remboursement'), ('payout', 'Cagnotte')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='proofs/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('is_synced', models.BooleanField(default=True)),
                ('local_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payout_date', models.DateTimeField()),
                ('cycle_position', models.PositiveIntegerField(help_text='Position dans le cycle')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tontines.cycle')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tontines.membership')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cagnotte',
                'verbose_name_plural': 'Cagnottes',
                'db_table': 'payouts',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transaction_type', models.CharField(choices=[('contribution', 'Cotisation'), ('refund', 'Remboursement'), ('payout', 'Cagnotte')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='proofs/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('is_synced', models.BooleanField(default=True)),
                ('local_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('days_participated', models.PositiveIntegerField()),
                ('penalty_rate_applied', models.FloatField()),
                ('processed_at', models.DateTimeField()),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tontines.cycle')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tontines.membership')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'db_table': 'refunds',
            },
        ),
    ]
