# Generated by Django 5.2.13 on 2026-04-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('participant', 'Participant'), ('admin', 'Administrateur')], default='participant', help_text='Type de compte utilisateur', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo_user',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/%Y/%m/'),
        ),
    ]
