# Generated by Django 5.2.13 on 2026-04-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_account_type_userprofile_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('participant', 'Participant'), ('admin', 'Administrateur')], default='participant', help_text='Type de compte utilisateur', max_length=20),
        ),
    ]
